<?php

namespace Database\Seeders;

use App\Models\MenuItem;
use Illuminate\Database\Seeder;

class MenuItemSeeder extends Seeder
{
    public function run(): void
    {
        $menuItems = [
            // Main Course
            [
                'name' => 'Nasi Gudeg Jogja',
                'description' => 'Nasi gudeg khas Jogja dengan ayam kampung, telur, dan sambal krecek',
                'price' => 25000,
                'calories' => 450,
                'protein' => 25.5,
                'carbs' => 55.2,
                'fat' => 12.8,
                'ingredients' => 'Nasi putih, gudeg, ayam kampung, telur, sambal krecek, kerupuk',
                'allergens' => json_encode(['gluten', 'eggs']),
                'image' => 'https://placehold.co/100',
                'is_available' => true,
                'dietary_tags' => json_encode(['halal', 'traditional']),
                'preparation_time' => 15,
                'spice_level' => 2,
                'category' => 'diet',
            ],
            [
                'name' => 'Ayam Bakar Taliwang',
                'description' => 'Ayam bakar khas Lombok dengan bumbu pedas dan nasi putih',
                'price' => 32000,
                'calories' => 520,
                'protein' => 35.2,
                'carbs' => 45.1,
                'fat' => 18.5,
                'ingredients' => 'Ayam kampung, bumbu taliwang, nasi putih, lalapan, sambal',
                'allergens' => json_encode([]),
                'image' => 'https://placehold.co/100',
                'is_available' => true,
                'dietary_tags' => json_encode(['halal', 'spicy']),
                'preparation_time' => 20,
                'spice_level' => 4,
                'category' => 'diet',
            ],
            [
                'name' => 'Rendang Daging Sapi',
                'description' => 'Rendang daging sapi empuk dengan bumbu rempah khas Padang',
                'price' => 38000,
                'calories' => 480,
                'protein' => 28.7,
                'carbs' => 35.8,
                'fat' => 22.3,
                'ingredients' => 'Daging sapi, santan, cabai, bawang, rempah-rempah, nasi putih',
                'allergens' => json_encode([]),
                'image' => 'https://placehold.co/100',
                'is_available' => true,
                'dietary_tags' => json_encode(['halal', 'spicy']),
                'preparation_time' => 25,
                'spice_level' => 3,
                'category' => 'protein',
            ],
            [
                'name' => 'Ikan Bakar Sambal Matah',
                'description' => 'Ikan kakap bakar dengan sambal matah khas Bali dan nasi putih',
                'price' => 35000,
                'calories' => 420,
                'protein' => 32.1,
                'carbs' => 38.5,
                'fat' => 15.2,
                'ingredients' => 'Ikan kakap, sambal matah, nasi putih, lalapan',
                'allergens' => json_encode(['fish']),
                'image' => 'https://placehold.co/100',
                'is_available' => true,
                'dietary_tags' => json_encode(['halal', 'seafood']),
                'preparation_time' => 18,
                'spice_level' => 2,
                'category' => 'protein',
            ],

            // Appetizers
            [
                'name' => 'Gado-Gado Jakarta',
                'description' => 'Salad sayuran dengan bumbu kacang khas Jakarta',
                'price' => 18000,
                'calories' => 280,
                'protein' => 12.5,
                'carbs' => 25.8,
                'fat' => 16.2,
                'ingredients' => 'Sayuran segar, tahu, tempe, telur, bumbu kacang, kerupuk',
                'allergens' => json_encode(['peanuts', 'eggs']),
                'image' => 'https://placehold.co/100',
                'is_available' => true,
                'dietary_tags' => json_encode(['vegetarian', 'healthy']),
                'preparation_time' => 10,
                'spice_level' => 1,
                'category' => 'protein',
            ],
            [
                'name' => 'Lumpia Semarang',
                'description' => 'Lumpia basah khas Semarang dengan isi rebung dan udang',
                'price' => 15000,
                'calories' => 220,
                'protein' => 8.5,
                'carbs' => 28.2,
                'fat' => 9.8,
                'ingredients' => 'Kulit lumpia, rebung, udang, telur, sayuran',
                'allergens' => json_encode(['gluten', 'shellfish', 'eggs']),
                'image' => 'https://placehold.co/100',
                'is_available' => true,
                'dietary_tags' => json_encode(['halal']),
                'preparation_time' => 12,
                'spice_level' => 1,
                'category' => 'diet',
            ],

            // Desserts
            [
                'name' => 'Es Cendol Durian',
                'description' => 'Es cendol dengan topping durian dan santan kental',
                'price' => 12000,
                'calories' => 180,
                'protein' => 3.2,
                'carbs' => 35.5,
                'fat' => 5.8,
                'ingredients' => 'Cendol, durian, santan, gula merah, es serut',
                'allergens' => json_encode([]),
                'image' => 'https://placehold.co/100',
                'is_available' => true,
                'dietary_tags' => json_encode(['vegetarian', 'sweet']),
                'preparation_time' => 5,
                'spice_level' => 0,
                'category' => 'royal',
            ],
            [
                'name' => 'Klepon Pandan',
                'description' => 'Klepon pandan dengan isian gula merah dan kelapa parut',
                'price' => 10000,
                'calories' => 150,
                'protein' => 2.8,
                'carbs' => 28.5,
                'fat' => 4.2,
                'ingredients' => 'Tepung ketan, pandan, gula merah, kelapa parut',
                'allergens' => json_encode([]),
                'image' => 'https://placehold.co/100',
                'is_available' => true,
                'dietary_tags' => json_encode(['vegetarian', 'traditional']),
                'preparation_time' => 8,
                'spice_level' => 0,
                'category' => 'royal',
            ],

            // Beverages
            [
                'name' => 'Es Teh Manis',
                'description' => 'Teh manis dingin yang menyegarkan',
                'price' => 5000,
                'calories' => 80,
                'protein' => 0.1,
                'carbs' => 20.5,
                'fat' => 0.0,
                'ingredients' => 'Teh, gula, es batu',
                'allergens' => json_encode([]),
                'image' => 'https://placehold.co/100',
                'is_available' => true,
                'dietary_tags' => json_encode(['vegetarian']),
                'preparation_time' => 3,
                'spice_level' => 0,
                'category' => 'diet',
            ],
            [
                'name' => 'Jus Alpukat',
                'description' => 'Jus alpukat segar dengan susu kental manis',
                'price' => 8000,
                'calories' => 120,
                'protein' => 2.5,
                'carbs' => 18.2,
                'fat' => 4.8,
                'ingredients' => 'Alpukat, susu kental manis, es batu',
                'allergens' => json_encode(['dairy']),
                'image' => 'https://placehold.co/100',
                'is_available' => true,
                'dietary_tags' => json_encode(['healthy']),
                'preparation_time' => 5,
                'spice_level' => 0,
                'category' => 'diet',
            ],

            // Healthy
            [
                'name' => 'Salad Quinoa Bowl',
                'description' => 'Bowl quinoa dengan sayuran segar dan dressing lemon',
                'price' => 28000,
                'calories' => 320,
                'protein' => 14.2,
                'carbs' => 42.8,
                'fat' => 8.5,
                'ingredients' => 'Quinoa, sayuran segar, alpukat, dressing lemon',
                'allergens' => json_encode([]),
                'image' => 'https://placehold.co/100',
                'is_available' => true,
                'dietary_tags' => json_encode(['healthy', 'vegetarian', 'gluten-free']),
                'preparation_time' => 12,
                'spice_level' => 0,
                'category' => 'diet',
            ],

            // Vegetarian
            [
                'name' => 'Nasi Pecel Madiun',
                'description' => 'Nasi dengan sayuran rebus dan bumbu pecel khas Madiun',
                'price' => 20000,
                'calories' => 380,
                'protein' => 15.8,
                'carbs' => 52.5,
                'fat' => 12.2,
                'ingredients' => 'Nasi putih, sayuran rebus, bumbu pecel, kerupuk, rempeyek',
                'allergens' => json_encode(['peanuts']),
                'image' => 'https://placehold.co/100',
                'is_available' => true,
                'dietary_tags' => json_encode(['vegetarian', 'traditional']),
                'preparation_time' => 10,
                'spice_level' => 2,
                'category' => 'diet',
            ],
        ];

        foreach ($menuItems as $item) {
            MenuItem::create($item);
        }
    }
}
